name: Run CI
on: [push, pull_request]

jobs:
  linter:
    runs-on: ubuntu-22.04
    if: ${{ github.event_name == 'pull_request' }}
    container: node:20
    steps:
      - uses: actions/checkout@v3
      - name: Run ESLint
        shell: bash
        run: |
          npm install
          
          ./node_modules/.bin/eslint --fix 'src/**/*.ts'

  build_dev_image:
    runs-on: ubuntu-22.04
    if: ${{ github.event_name == 'pull_request' }}
    container: node:20
    steps:
      - uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "build dev image"
        shell: bash
        run: |
          make build \
            PLATFORMS=linux/amd64,linux/arm64 \
            LOAD_TARGET=registry \
            PUSH_TO_REGISTRY=true \
            VERSION=$(git rev-parse --short ${{ github.event.pull_request.head.sha }})

  build_release_image:
    runs-on: ubuntu-22.04
    if: ${{ github.event_name == 'push' && contains(github.ref, 'refs/tags/') }}
    container: node:20
    steps:
      - uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "build production image"
        shell: bash
        run: |
          make build \
            PLATFORMS=linux/amd64,linux/arm64 \
            LOAD_TARGET=registry \
            PUSH_TO_REGISTRY=true \
            VERSION=$(git describe --tags --abbrev=0)
