name: Run CI
on: [push, pull_request]

jobs:
  linter:
    runs-on: ubuntu-22.04
    if: ${{ github.event_name == 'pull_request' || github.ref == 'refs/heads/main' }}
    container: node:20
    steps:
      - uses: actions/checkout@v3
      - name: Run ESLint
        shell: bash
        run: |
          npm install
          
          ./node_modules/.bin/eslint --fix 'src/**/*.ts'

  build_dev_image:
    runs-on: ubuntu-22.04
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "build dev image"
        shell: bash
        run: |
          VERSION=$(git rev-parse --short ${{ github.event.pull_request.head.sha }})
          
          docker buildx build . \
            --platform linux/amd64,linux/arm64 \
            --tag ghcr.io/$GITHUB_REPOSITORY:$VERSION \
            --tag ghcr.io/$GITHUB_REPOSITORY:latest \
            --push

  build_release_image:
    runs-on: ubuntu-22.04
    if: ${{ github.event_name == 'push' && contains(github.ref, 'refs/tags/') }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "build production image"
        shell: bash
        run: |
          docker buildx build . \
            --platform linux/amd64,linux/arm64 \
            --tag ghcr.io/$GITHUB_REPOSITORY:$GITHUB_REF_NAME \
            --tag ghcr.io/$GITHUB_REPOSITORY:latest \
            --push
